//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated. 
// </auto-generated>
//------------------------------------------------------------------------------

namespace Borouge.Internet.Main.WebParts.AboutUs.Borouge2030StrategyWP
{


    public partial class Borouge2030StrategyWPUserControl
    {
    }
}
