//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Borouge.Internet.Main.WebParts.Home.EveryDayLifeWP {
    using System.Web.UI.WebControls.Expressions;
    using System.Web.UI.HtmlControls;
    using System.Collections;
    using System.Text;
    using System.Web.UI;
    using System.Collections.Generic;
    using System.Linq;
    using System.Xml.Linq;
    using Microsoft.SharePoint.WebPartPages;
    using System.Web.SessionState;
    using System.Configuration;
    using Microsoft.SharePoint;
    using System.Web;
    using System.Web.DynamicData;
    using System.Web.Caching;
    using System.Web.Profile;
    using System.ComponentModel.DataAnnotations;
    using System.Web.UI.WebControls;
    using System.Web.Security;
    using System;
    using Microsoft.SharePoint.Utilities;
    using System.Text.RegularExpressions;
    using System.Collections.Specialized;
    using System.Web.UI.WebControls.WebParts;
    using Microsoft.SharePoint.WebControls;
    using System.CodeDom.Compiler;
    
    
    public partial class EveryDayLifeWP {
        
        [GeneratedCodeAttribute("Microsoft.VisualStudio.SharePoint.ProjectExtensions.CodeGenerators.SharePointWebPartCodeGenerator", "16.0.0.0")]
        public static implicit operator global::System.Web.UI.TemplateControl(EveryDayLifeWP target) 
        {
            return target == null ? null : target.TemplateControl;
        }
        
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Never)]
        [GeneratedCodeAttribute("Microsoft.VisualStudio.SharePoint.ProjectExtensions.CodeGenerators.SharePointWebP" +
            "artCodeGenerator", "16.0.0.0")]
        private void @__BuildControlTree(global::Borouge.Internet.Main.WebParts.Home.EveryDayLifeWP.EveryDayLifeWP @__ctrl) {
            System.Web.UI.IParserAccessor @__parser = ((System.Web.UI.IParserAccessor)(@__ctrl));
            @__parser.AddParsedSubObject(new System.Web.UI.LiteralControl("\r\n\r\n\r\n\r\n<div class=\"placeholder placeholder--no-padding\">\r\n      <section class=\"" +
                        "banner-video-popup-widget\">\r\n        <div class=\"container h-100\">\r\n          <d" +
                        "iv class=\"row justify-content-center mb-4\">\r\n            <div class=\"col-md-8 te" +
                        "xt-center\">\r\n              <h2 class=\"fw-normal mb-3\">We enable<span class=\"fw-s" +
                        "emi\"> every day life</span></h2>\r\n              <p>Lorem ipsum dolor sit amet, c" +
                        "onsectetur adipiscing elit. Et tincidunt odio et nulla vitae eget pellentesque. " +
                        "Dolor aliquam enim nec sagittis vitae. Est viverra in odio volutpat aliquet um.<" +
                        "/p>\r\n            </div>\r\n          </div>\r\n          <div class=\"row\">\r\n        " +
                        "    <div class=\"col-12\">\r\n              <div class=\"video-banner mb-3\"><img clas" +
                        "s=\"video-banner__img\" src=\"/sites/BorougeDev/Style%20Library/assets/Borouge/imag" +
                        "es/bg-video.jpg\" alt=\"\">\r\n                <button class=\"btn btn--circle btn--ci" +
                        "rcle-large bg-white position-absolute top-50 start-50 translate-middle video-ban" +
                        "ner__play\" data-bs-toggle=\"modal\" data-bs-target=\".video-banner-modal\"><span cla" +
                        "ss=\"ic ic-48 ic-play\"></span></button>\r\n              </div>\r\n            </div>" +
                        "\r\n          </div>\r\n          <div class=\"row\">\r\n            <div class=\"col-12\"" +
                        ">\r\n              <h3 class=\"mb-1\">Lorem Ipsum Dolor Esit.</h3>\r\n              <p" +
                        ">Lorem ipsum dolor sit amet, consectetur adipiscing elit. Et tincidunt odio et n" +
                        "ulla vitae eget pellentesque. Dolor aliquam enim nec sagittis vitae. Est viverra" +
                        " in odio volutpat aliquet um.</p>\r\n              <div class=\"text-center mt-3\">\r" +
                        "\n                <div class=\"btn btn--primary text-uppercase\">Find Out More</div" +
                        ">\r\n              </div>\r\n            </div>\r\n          </div>\r\n        </div>\r\n " +
                        "     </section>\r\n    </div>"));
        }
        
        [GeneratedCodeAttribute("Microsoft.VisualStudio.SharePoint.ProjectExtensions.CodeGenerators.SharePointWebP" +
            "artCodeGenerator", "16.0.0.0")]
        private void InitializeControl() {
            this.@__BuildControlTree(this);
            this.Load += new global::System.EventHandler(this.Page_Load);
        }
        
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Never)]
        [GeneratedCodeAttribute("Microsoft.VisualStudio.SharePoint.ProjectExtensions.CodeGenerators.SharePointWebP" +
            "artCodeGenerator", "16.0.0.0")]
        protected virtual object Eval(string expression) {
            return global::System.Web.UI.DataBinder.Eval(this.Page.GetDataItem(), expression);
        }
        
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Never)]
        [GeneratedCodeAttribute("Microsoft.VisualStudio.SharePoint.ProjectExtensions.CodeGenerators.SharePointWebP" +
            "artCodeGenerator", "16.0.0.0")]
        protected virtual string Eval(string expression, string format) {
            return global::System.Web.UI.DataBinder.Eval(this.Page.GetDataItem(), expression, format);
        }
    }
}
